sudo: required

services:
  - docker

before_install:
  - docker build -t danielhyunchae/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielhyunchae/multi-test npm test

after-succes:
  - docker build -t danielhyunchae/multi-client ./client
  - docker build -t danielhyunchae/multi-nginx ./nginx
  - docker build -t danielhyunchae/multi-server ./server
  - docker build -t danielhyunchae/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push image to dockerhub
  - docker push danielhyunchae/multi-client
  - docker push danielhyunchae/multi-nginx
  - docker push danielhyunchae/multi-server
  - docker push danielhyunchae/multi-worker

#Tell travis how to deploy our code to AWS
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket-name: "elasticbeanstalk-us-east-2-829092469475"
  bucket-path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
